[2023-06-09T00:34:55.461+0200] {processor.py:156} INFO - Started process (PID=21275) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:34:55.461+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:34:55.461+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:34:55.461+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:34:55.616+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:34:55.615+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:34:55.617+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:34:55.664+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.206 seconds
[2023-06-09T00:35:06.579+0200] {processor.py:156} INFO - Started process (PID=21287) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:06.614+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:35:06.615+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:06.615+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:06.826+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:06.824+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:35:06.827+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:06.873+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.296 seconds
[2023-06-09T00:35:19.291+0200] {processor.py:156} INFO - Started process (PID=21300) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:19.292+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:35:19.292+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:19.292+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:19.466+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:19.464+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:35:19.467+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:19.489+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.200 seconds
[2023-06-09T00:35:33.866+0200] {processor.py:156} INFO - Started process (PID=21313) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:33.867+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:35:33.867+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:33.867+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:34.087+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:34.085+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:35:34.089+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:34.102+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.238 seconds
[2023-06-09T00:35:52.431+0200] {processor.py:156} INFO - Started process (PID=21329) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:52.432+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:35:52.433+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:52.433+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:52.683+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:35:52.680+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:35:52.684+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:35:52.750+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.322 seconds
[2023-06-09T00:36:09.300+0200] {processor.py:156} INFO - Started process (PID=21343) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:09.301+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:36:09.302+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:36:09.302+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:09.520+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:36:09.518+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:36:09.521+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:09.586+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.289 seconds
[2023-06-09T00:36:26.730+0200] {processor.py:156} INFO - Started process (PID=21358) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:26.731+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:36:26.731+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:36:26.731+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:26.962+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:36:26.960+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:36:26.964+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:27.028+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.301 seconds
[2023-06-09T00:36:44.171+0200] {processor.py:156} INFO - Started process (PID=21373) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:44.172+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:36:44.172+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:36:44.172+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:44.390+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:36:44.389+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:36:44.392+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:36:44.404+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.235 seconds
[2023-06-09T00:37:00.041+0200] {processor.py:156} INFO - Started process (PID=21387) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:00.042+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:37:00.043+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:00.043+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:00.244+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:00.242+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:37:00.245+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:00.312+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.273 seconds
[2023-06-09T00:37:15.366+0200] {processor.py:156} INFO - Started process (PID=21401) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:15.384+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:37:15.385+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:15.385+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:15.572+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:15.570+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:37:15.573+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:15.639+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.275 seconds
[2023-06-09T00:37:31.897+0200] {processor.py:156} INFO - Started process (PID=21415) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:31.897+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:37:31.898+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:31.898+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:32.101+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:32.099+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:37:32.102+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:32.168+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.273 seconds
[2023-06-09T00:37:47.776+0200] {processor.py:156} INFO - Started process (PID=21429) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:47.776+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:37:47.777+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:47.777+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:47.970+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:37:47.969+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:37:47.971+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:37:47.993+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.220 seconds
[2023-06-09T00:38:03.956+0200] {processor.py:156} INFO - Started process (PID=21748) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:03.993+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:38:03.994+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:03.994+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:04.217+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:04.215+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:38:04.218+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:04.280+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.327 seconds
[2023-06-09T00:38:20.160+0200] {processor.py:156} INFO - Started process (PID=21762) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:20.161+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:38:20.161+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:20.161+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:20.386+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:20.384+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:38:20.387+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:20.400+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.243 seconds
[2023-06-09T00:38:37.148+0200] {processor.py:156} INFO - Started process (PID=22022) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:37.177+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:38:37.177+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:37.177+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:37.381+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:37.380+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:38:37.382+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:37.428+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.282 seconds
[2023-06-09T00:38:54.800+0200] {processor.py:156} INFO - Started process (PID=22039) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:54.801+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:38:54.801+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:54.801+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:54.969+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:38:54.968+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:38:54.970+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:38:55.015+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.217 seconds
[2023-06-09T00:39:10.028+0200] {processor.py:156} INFO - Started process (PID=22346) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:10.029+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:39:10.029+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:10.029+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:10.232+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:10.230+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:39:10.233+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:10.245+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.220 seconds
[2023-06-09T00:39:24.283+0200] {processor.py:156} INFO - Started process (PID=22441) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:24.319+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:39:24.320+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:24.320+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:24.474+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:24.471+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:39:24.476+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:24.524+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.243 seconds
[2023-06-09T00:39:42.655+0200] {processor.py:156} INFO - Started process (PID=22458) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:42.656+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:39:42.657+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:42.657+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:42.864+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:42.862+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:39:42.866+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:42.917+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.265 seconds
[2023-06-09T00:39:58.280+0200] {processor.py:156} INFO - Started process (PID=22706) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:58.316+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:39:58.316+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:58.316+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:58.520+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:39:58.518+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:39:58.522+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:39:58.568+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.291 seconds
[2023-06-09T00:40:11.574+0200] {processor.py:156} INFO - Started process (PID=22720) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:11.574+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:40:11.575+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:40:11.575+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:11.772+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:40:11.770+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:40:11.774+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:11.785+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.214 seconds
[2023-06-09T00:40:26.042+0200] {processor.py:156} INFO - Started process (PID=22734) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:26.068+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:40:26.069+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:40:26.069+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:26.247+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:40:26.246+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:40:26.248+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:26.295+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.255 seconds
[2023-06-09T00:40:43.781+0200] {processor.py:156} INFO - Started process (PID=22748) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:43.782+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:40:43.782+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:40:43.782+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:43.959+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:40:43.958+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:40:43.960+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:40:43.971+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.192 seconds
[2023-06-09T00:41:01.772+0200] {processor.py:156} INFO - Started process (PID=23089) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:01.773+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:41:01.774+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:01.774+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:01.972+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:01.971+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:41:01.974+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:02.021+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.251 seconds
[2023-06-09T00:41:20.839+0200] {processor.py:156} INFO - Started process (PID=23111) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:20.839+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:41:20.840+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:20.840+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:21.029+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:21.027+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:41:21.031+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:21.041+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.204 seconds
[2023-06-09T00:41:38.940+0200] {processor.py:156} INFO - Started process (PID=23318) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:38.976+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:41:38.977+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:38.977+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:39.188+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:39.187+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:41:39.189+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:39.235+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.297 seconds
[2023-06-09T00:41:55.076+0200] {processor.py:156} INFO - Started process (PID=23334) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:55.076+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:41:55.077+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:55.077+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:55.280+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:41:55.279+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:41:55.281+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:41:55.326+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.253 seconds
[2023-06-09T00:42:09.697+0200] {processor.py:156} INFO - Started process (PID=23348) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:09.698+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:42:09.699+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:09.698+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:09.899+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:09.898+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:42:09.900+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:09.948+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.254 seconds
[2023-06-09T00:42:24.128+0200] {processor.py:156} INFO - Started process (PID=23361) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:24.129+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:42:24.129+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:24.129+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:24.336+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:24.335+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:42:24.337+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:24.384+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.259 seconds
[2023-06-09T00:42:42.249+0200] {processor.py:156} INFO - Started process (PID=23376) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:42.249+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:42:42.250+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:42.250+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:42.473+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:42.470+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:42:42.474+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:42.525+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.279 seconds
[2023-06-09T00:42:59.014+0200] {processor.py:156} INFO - Started process (PID=23390) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:59.052+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:42:59.053+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:59.053+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:59.218+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:42:59.217+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:42:59.220+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:42:59.276+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.264 seconds
[2023-06-09T00:43:15.258+0200] {processor.py:156} INFO - Started process (PID=23406) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:15.258+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:43:15.259+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:43:15.259+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:15.418+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:43:15.417+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:43:15.420+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:15.464+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.208 seconds
[2023-06-09T00:43:29.811+0200] {processor.py:156} INFO - Started process (PID=23419) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:29.812+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:43:29.812+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:43:29.812+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:30.010+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:43:30.009+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:43:30.012+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:30.060+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.251 seconds
[2023-06-09T00:43:43.971+0200] {processor.py:156} INFO - Started process (PID=23432) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:44.007+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:43:44.008+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:43:44.008+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:44.172+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:43:44.170+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:43:44.173+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:43:44.216+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.248 seconds
[2023-06-09T00:44:01.971+0200] {processor.py:156} INFO - Started process (PID=23447) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:01.971+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:44:01.971+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:01.971+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:02.171+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:02.170+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:44:02.172+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:02.219+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.250 seconds
[2023-06-09T00:44:18.881+0200] {processor.py:156} INFO - Started process (PID=23461) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:18.917+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:44:18.918+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:18.918+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:19.106+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:19.105+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:44:19.108+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:19.167+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.287 seconds
[2023-06-09T00:44:35.748+0200] {processor.py:156} INFO - Started process (PID=23788) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:35.751+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:44:35.752+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:35.752+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:35.993+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:35.991+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:44:35.994+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:36.063+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.318 seconds
[2023-06-09T00:44:51.068+0200] {processor.py:156} INFO - Started process (PID=23803) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:51.068+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:44:51.069+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:51.069+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:51.278+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:44:51.276+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:44:51.279+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:44:51.345+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.279 seconds
[2023-06-09T00:45:05.411+0200] {processor.py:156} INFO - Started process (PID=23816) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:05.447+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:45:05.448+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:05.447+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:05.680+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:05.679+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:45:05.681+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:05.692+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.284 seconds
[2023-06-09T00:45:21.798+0200] {processor.py:156} INFO - Started process (PID=23831) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:21.799+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:45:21.799+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:21.799+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:22.011+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:22.010+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:45:22.013+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:22.081+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.286 seconds
[2023-06-09T00:45:37.575+0200] {processor.py:156} INFO - Started process (PID=23845) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:37.575+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:45:37.576+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:37.576+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:37.778+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:37.777+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:45:37.780+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:37.846+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.273 seconds
[2023-06-09T00:45:53.513+0200] {processor.py:156} INFO - Started process (PID=23859) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:53.548+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:45:53.549+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:53.549+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:53.731+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:45:53.729+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:45:53.732+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:45:53.815+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.306 seconds
[2023-06-09T00:46:09.180+0200] {processor.py:156} INFO - Started process (PID=23873) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:09.180+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:46:09.181+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:09.181+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:09.392+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:09.390+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:46:09.394+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:09.407+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.230 seconds
[2023-06-09T00:46:26.391+0200] {processor.py:156} INFO - Started process (PID=23887) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:26.426+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:46:26.427+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:26.427+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:26.629+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:26.627+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:46:26.630+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:26.642+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.253 seconds
[2023-06-09T00:46:42.139+0200] {processor.py:156} INFO - Started process (PID=24214) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:42.139+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:46:42.140+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:42.140+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:42.350+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:42.348+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:46:42.351+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:42.380+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.244 seconds
[2023-06-09T00:46:57.757+0200] {processor.py:156} INFO - Started process (PID=25322) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:57.758+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:46:57.759+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:57.758+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:57.968+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:46:57.966+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:46:57.969+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:46:58.036+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.281 seconds
[2023-06-09T00:47:13.626+0200] {processor.py:156} INFO - Started process (PID=25336) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:13.663+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:47:13.664+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:47:13.663+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:13.862+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:47:13.860+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:47:13.863+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:13.907+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.283 seconds
[2023-06-09T00:47:30.736+0200] {processor.py:156} INFO - Started process (PID=25350) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:30.737+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:47:30.737+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:47:30.737+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:30.940+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:47:30.938+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:47:30.941+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:30.989+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.255 seconds
[2023-06-09T00:47:47.534+0200] {processor.py:156} INFO - Started process (PID=25365) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:47.535+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:47:47.536+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:47:47.535+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:47.735+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:47:47.733+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:47:47.737+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:47:47.782+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.250 seconds
[2023-06-09T00:48:04.593+0200] {processor.py:156} INFO - Started process (PID=25380) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:04.594+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:48:04.594+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:04.594+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:04.785+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:04.783+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:48:04.786+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:04.834+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.242 seconds
[2023-06-09T00:48:18.345+0200] {processor.py:156} INFO - Started process (PID=25394) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:18.346+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:48:18.346+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:18.346+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:18.527+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:18.525+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:48:18.528+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:18.575+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.232 seconds
[2023-06-09T00:48:34.818+0200] {processor.py:156} INFO - Started process (PID=26197) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:34.819+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:48:34.820+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:34.820+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:35.033+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:35.032+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:48:35.035+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:35.048+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.232 seconds
[2023-06-09T00:48:51.960+0200] {processor.py:156} INFO - Started process (PID=26231) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:51.960+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:48:51.961+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:51.961+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:52.170+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:48:52.169+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:48:52.171+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:48:52.185+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.228 seconds
[2023-06-09T00:49:07.811+0200] {processor.py:156} INFO - Started process (PID=26411) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:07.846+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:49:07.847+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:49:07.847+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:08.060+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:49:08.059+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:49:08.061+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:08.106+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.297 seconds
[2023-06-09T00:49:23.325+0200] {processor.py:156} INFO - Started process (PID=26426) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:23.326+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:49:23.326+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:49:23.326+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:23.536+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:49:23.535+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver.exe')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:49:23.538+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:23.583+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.260 seconds
[2023-06-09T00:49:40.422+0200] {processor.py:156} INFO - Started process (PID=26724) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:40.422+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:49:40.423+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:49:40.423+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:40.423+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:49:40.423+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:49:40.423+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:49:40.462+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.042 seconds
[2023-06-09T00:54:56.529+0200] {processor.py:156} INFO - Started process (PID=29541) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:54:56.565+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:54:56.565+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:54:56.565+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:54:56.689+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:54:56.686+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:54:56.690+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:54:56.737+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.210 seconds
[2023-06-09T00:55:06.646+0200] {processor.py:156} INFO - Started process (PID=29553) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:06.647+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:55:06.647+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:06.647+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:06.772+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:06.769+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:55:06.773+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:06.787+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.143 seconds
[2023-06-09T00:55:17.871+0200] {processor.py:156} INFO - Started process (PID=29565) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:17.871+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:55:17.872+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:17.872+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:17.980+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:17.978+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:55:17.982+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:17.996+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.127 seconds
[2023-06-09T00:55:29.555+0200] {processor.py:156} INFO - Started process (PID=29577) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:29.591+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:55:29.592+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:29.592+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:29.721+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:29.720+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:55:29.722+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:29.771+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.219 seconds
[2023-06-09T00:55:39.951+0200] {processor.py:156} INFO - Started process (PID=29597) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:39.985+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:55:39.986+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:39.986+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:40.111+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:40.110+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:55:40.112+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:40.161+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.213 seconds
[2023-06-09T00:55:51.941+0200] {processor.py:156} INFO - Started process (PID=29610) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:51.942+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:55:51.943+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:51.942+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:52.049+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:55:52.048+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:55:52.050+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:55:52.064+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.125 seconds
[2023-06-09T00:56:03.568+0200] {processor.py:156} INFO - Started process (PID=29939) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:03.569+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:56:03.570+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:03.569+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:03.696+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:03.695+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:56:03.697+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:03.747+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.181 seconds
[2023-06-09T00:56:16.804+0200] {processor.py:156} INFO - Started process (PID=30203) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:16.838+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:56:16.839+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:16.839+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:16.963+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:16.961+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:56:16.964+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:17.018+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.217 seconds
[2023-06-09T00:56:30.938+0200] {processor.py:156} INFO - Started process (PID=30216) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:30.945+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:56:30.946+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:30.946+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:31.085+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:31.084+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:56:31.087+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:31.136+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.200 seconds
[2023-06-09T00:56:45.491+0200] {processor.py:156} INFO - Started process (PID=30542) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:45.491+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:56:45.492+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:45.492+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:45.609+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:45.607+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:56:45.610+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:45.624+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.136 seconds
[2023-06-09T00:56:58.530+0200] {processor.py:156} INFO - Started process (PID=30556) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:58.530+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:56:58.531+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:58.531+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:58.647+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:56:58.646+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:56:58.648+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:56:58.661+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.133 seconds
[2023-06-09T00:57:10.436+0200] {processor.py:156} INFO - Started process (PID=30568) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:10.474+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:57:10.475+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:57:10.475+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:10.611+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:57:10.609+0200] {dagbag.py:330} ERROR - Failed to import: /home/rohan/airflow/dags/lib/data_fetcher.py
Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 161, in <module>
    connexion_twitter()
  File "/home/rohan/airflow/dags/lib/data_fetcher.py", line 13, in connexion_twitter
    driver = webdriver.Chrome('//wsl.localhost/Ubuntu/home/rohan/airflow/dags/lib/chromedriver')
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "/home/rohan/airflow_venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
[2023-06-09T00:57:10.612+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:10.665+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.231 seconds
[2023-06-09T00:57:23.124+0200] {processor.py:156} INFO - Started process (PID=30579) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:23.124+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:57:23.125+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:57:23.125+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:23.126+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:23.160+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.039 seconds
[2023-06-09T00:57:36.420+0200] {processor.py:156} INFO - Started process (PID=30897) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:36.421+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:57:36.421+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:57:36.421+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:36.421+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:57:36.421+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:57:36.421+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:36.430+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.012 seconds
[2023-06-09T00:57:49.794+0200] {processor.py:156} INFO - Started process (PID=30921) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:49.796+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:57:49.796+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:57:49.796+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:49.797+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:57:49.797+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:57:49.797+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:57:49.804+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.013 seconds
[2023-06-09T00:58:03.609+0200] {processor.py:156} INFO - Started process (PID=31216) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:03.646+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:58:03.647+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:03.646+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:03.647+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:03.647+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:58:03.647+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:03.655+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.048 seconds
[2023-06-09T00:58:16.625+0200] {processor.py:156} INFO - Started process (PID=31231) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:16.626+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:58:16.627+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:16.627+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:16.627+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:16.627+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:58:16.628+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:16.638+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.016 seconds
[2023-06-09T00:58:27.558+0200] {processor.py:156} INFO - Started process (PID=31475) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:27.594+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:58:27.595+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:27.595+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:27.595+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:27.595+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:58:27.596+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:27.603+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.048 seconds
[2023-06-09T00:58:39.897+0200] {processor.py:156} INFO - Started process (PID=31505) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:39.898+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:58:39.898+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:39.898+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:39.899+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:39.899+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:58:39.899+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:39.907+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.012 seconds
[2023-06-09T00:58:53.278+0200] {processor.py:156} INFO - Started process (PID=31536) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:53.279+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:58:53.279+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:53.279+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:53.280+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:58:53.280+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:58:53.280+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:58:53.287+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.011 seconds
[2023-06-09T00:59:07.914+0200] {processor.py:156} INFO - Started process (PID=31567) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:07.950+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:59:07.950+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:07.950+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:07.951+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:07.951+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:59:07.951+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:07.957+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.046 seconds
[2023-06-09T00:59:23.464+0200] {processor.py:156} INFO - Started process (PID=31598) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:23.465+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:59:23.465+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:23.465+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:23.465+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:23.465+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:59:23.465+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:23.472+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.010 seconds
[2023-06-09T00:59:40.336+0200] {processor.py:156} INFO - Started process (PID=31630) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:40.336+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:59:40.337+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:40.337+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:40.337+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:40.337+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:59:40.337+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:40.344+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.011 seconds
[2023-06-09T00:59:53.470+0200] {processor.py:156} INFO - Started process (PID=31660) to work on /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:53.506+0200] {processor.py:758} INFO - Processing file /home/rohan/airflow/dags/lib/data_fetcher.py for tasks to queue
[2023-06-09T00:59:53.507+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:53.507+0200] {dagbag.py:525} INFO - Filling up the DagBag from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:53.507+0200] {logging_mixin.py:117} INFO - [2023-06-09T00:59:53.507+0200] {dagbag.py:307} INFO - File /home/rohan/airflow/dags/lib/data_fetcher.py assumed to contain no DAGs. Skipping.
[2023-06-09T00:59:53.507+0200] {processor.py:770} WARNING - No viable dags retrieved from /home/rohan/airflow/dags/lib/data_fetcher.py
[2023-06-09T00:59:53.516+0200] {processor.py:178} INFO - Processing /home/rohan/airflow/dags/lib/data_fetcher.py took 0.048 seconds
